apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${FRONTEND_NAME}-ingress
  namespace: ${NAMESPACE}
spec:
  ingressClassName: nginx
  rules:
    - host: frontend.todo-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${FRONTEND_NAME}
                port:
                  number: 80
