apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ${NAMESPACE}

spec:
  selector:
    app: todomanagement-frontend

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP
