apiVersion: v1
kind: Service
metadata:
  name: ${FRONTEND_NAME}
  namespace: ${NAMESPACE}

spec:
  selector:
    app: ${FRONTEND_NAME}

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP
