variables:
  FRONTEND_NAME: "todomanagement-frontend"
  NAMESPACE: "todo-test"
  FRONTEND_IMAGE: "$CI_REGISTRY_IMAGE/${FRONTEND_NAME}:${CI_PIPELINE_ID}"

# -------------------------
# BUILD FRONTEND
# -------------------------
build-frontend:
  image: docker:27
  stage: build
  services:
    - name: docker:27.5.1-dind
      alias: docker
      command: ["--tls=false","--mtu=1410"]

  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

  tags:
    - k8s

  before_script:
    - echo -n "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

  script:
    - docker info
    - cd frontend
    - docker build -t "$FRONTEND_IMAGE" .
    - docker push "$FRONTEND_IMAGE" || docker push "$IMAGE_PATH"

  timeout: 20 minutes

# -------------------------
# DEPLOY FRONTEND
# -------------------------
deploy-frontend:
  stage: deploy-frontend
  image: devopshepsiburada/kubectl:1.25.0
  tags:
    - k8s
  before_script:
    - kubectl config use-context $CI_PROJECT_ROOT_NAMESPACE/gitlab-agents:retail-hke-test
  script:
    - kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
    - kubectl get secret retail-gitlab -n "$NAMESPACE" >/dev/null 2>&1 || kubectl create secret docker-registry retail-gitlab --docker-server="$CI_REGISTRY" --docker-username="$DEPLOY_USERNAME" --docker-password="$DEPLOY_PASSWORD" -n "$NAMESPACE"
    - envsubst < frontend/.k8s/deployment.yaml > actual_deployment.yaml
    - echo "--- DEBUG IMAGE NAME ---"
    - grep "image:" actual_deployment.yaml
    - kubectl apply -f actual_deployment.yaml
    - envsubst < frontend/.k8s/service.yaml | kubectl apply -f -
    - envsubst < frontend/.k8s/ingress.yaml | kubectl apply -f -
    - echo "⏳ Monitoring pod status..."
    - for i in $(seq 1 20); do POD_DATA=$(kubectl get pods -n "$NAMESPACE" -l app=$FRONTEND_NAME --no-headers | head -n 1); STATUS=$(echo $POD_DATA | awk '{print $3}'); READY=$(echo $POD_DATA | awk '{print $2}'); echo "Step $i - Status:$STATUS ($READY)"; if [ "$READY" == "1/1" ]; then echo "✅ Success!"; exit 0; fi; if [ "$STATUS" == "ImagePullBackOff" ] || [ "$STATUS" == "ErrImagePull" ]; then echo "❌ Image Error!"; kubectl describe pod -n "$NAMESPACE" -l app=$FRONTEND_NAME; exit 1; fi; sleep 5; done; echo "❌ Timeout!"; kubectl describe pod -n "$NAMESPACE" -l app=$FRONTEND_NAME; exit 1
    - kubectl port-forward svc/todomanagement-frontend 8082:80 -n todo-test
  timeout: 20 minutes