stages:
  - build
  - deploy-test
  - deploy-gateway
  - build-frontend
  - deploy-frontend


include:
  - local: '/backend/.gitlab-ci.yml'
  - local: '/gateway/.gitlab-ci.yml'
  - local: '/frontend/.gitlab-ci.yml'
    
  