stages:
  - build
  - deploy-backend
  - deploy-gateway
  - build-frontend
  


include:
  - local: '/backend/.gitlab-ci.yml'
  - local: '/gateway/.gitlab-ci.yml'
  - local: '/frontend/.gitlab-ci.yml'
    
  