apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: todomanagement-api
spec:
  replicas: 1

  strategy:
    type: Recreate   # 🔥 ROLLOUT BUG FIX

  selector:
    matchLabels:
      app: todomanagement-api

  template:
    metadata:
      labels:
        app: todomanagement-api
    spec:
      terminationGracePeriodSeconds: 15   # 🔥 OLD POD KAPANABİLSİN

      containers:
        - name: ${APP_NAME}
          image: ${IMAGE_PATH}
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:                    # 🧠 STABILITY
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

      imagePullSecrets:
        - name: retail-gitlab
