apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${BACKEND_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${BACKEND_NAME}

spec:
  replicas: 1

  strategy:
    type: Recreate
    

  selector:
    matchLabels:
      app: ${BACKEND_NAME}

  template:
    metadata:
      labels:
        app: ${BACKEND_NAME}

    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: retail-gitlab

      containers:
        - name: ${BACKEND_NAME}
          image: ${IMAGE_PATH}
          imagePullPolicy: Always

          env:
            - name: ENV
              value: test
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: MongoDb__ConnectionString
              value: mongodb://mongo:27017
            - name: MongoDb__Database
              value: TodoManagement
            - name: Redis__ConnectionString
              value: redis:6379,abortConnect=false

          ports:
            - containerPort: 8080
              protocol: TCP

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          # -----------------------
          # READINESS PROBE
          # -----------------------
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          # -----------------------
          # LIVENESS PROBE
          # -----------------------
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

      
