variables:
  NAMESPACE: "todo-test"

deploy-gateway:
  stage: deploy-gateway
  image: devopshepsiburada/kubectl:1.25.0
  tags:
    - k8s

  before_script:
    - kubectl config use-context $CI_PROJECT_ROOT_NAMESPACE/gitlab-agents:retail-hke-test
    


  script:
    - kubectl delete deployment krakend -n "$NAMESPACE" --ignore-not-found=true
    - kubectl delete service krakend -n "$NAMESPACE" --ignore-not-found=true
    - envsubst '$NAMESPACE' < gateway/.k8s/krakend-config.yaml | kubectl apply -f -
    - envsubst '$NAMESPACE' < gateway/.k8s/deployment.yaml | kubectl apply -f -
    - envsubst '$NAMESPACE' < gateway/.k8s/service.yaml | kubectl apply -f -
    - kubectl get configmap krakend-config -n "$NAMESPACE" -o yaml

    - kubectl get pods -n "$NAMESPACE"
    - kubectl describe pod -n "$NAMESPACE" -l app=krakend
    - kubectl logs -n "$NAMESPACE" deployment/krakend
    - kubectl rollout restart deployment/krakend -n "$NAMESPACE"
    - kubectl describe pod -n "$NAMESPACE" krakend-67b5c9796d-kxtvj
    
    - kubectl describe pod krakend-6c97f4c597-7jzj8 -n todo-test



    - kubectl rollout status deployment/krakend -n "$NAMESPACE" --timeout=180s

  timeout: 10 minutes
