variables:
  GATEWAY_NAME: "krakend"
  NAMESPACE: "todo-test"
  GATEWAY_IMAGE: "$CI_REGISTRY_IMAGE/${GATEWAY_NAME}:${CI_PIPELINE_ID}"

# -------------------------
# BUILD GATEWAY
# -------------------------
build-gateway:
  image: docker:27
  stage: build
  services:
    - name: docker:27.5.1-dind
      alias: docker
      command: ["--tls=false","--mtu=1410"]

  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

  tags:
    - k8s

  before_script:
    - echo -n "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

  script:
    - docker info
    - cd gateway
    - docker build -t "$GATEWAY_IMAGE" .
    - docker push "$GATEWAY_IMAGE"

  timeout: 20 minutes

# -------------------------
# DEPLOY GATEWAY
# -------------------------
deploy-gateway:
  stage: deploy-gateway
  image: devopshepsiburada/kubectl:1.25.0
  tags:
    - k8s

  before_script:
    - kubectl config use-context $CI_PROJECT_ROOT_NAMESPACE/gitlab-agents:retail-hke-test

  script:
    - kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -


    - kubectl get secret retail-gitlab -n "$NAMESPACE" >/dev/null 2>&1 || kubectl create secret docker-registry retail-gitlab --docker-server="$CI_REGISTRY" --docker-username="$DEPLOY_USERNAME" --docker-password="$DEPLOY_PASSWORD" -n "$NAMESPACE"
    - kubectl apply -f gateway/.k8s/krakend-config.yaml

    - envsubst < gateway/.k8s/deployment.yaml | kubectl apply -f -
    - envsubst < gateway/.k8s/service.yaml | kubectl apply -f -
    - envsubst < gateway/.k8s/ingress.yaml | kubectl apply -f -

   

    - echo "📦 Gateway node IP:"
    - kubectl get nodes -o wide
    - echo "📦 Gateway Pods:"
    - kubectl get pods -n "$NAMESPACE"

    - echo "📜 Gateway Logs:"
    - kubectl logs -n "$NAMESPACE" -l app=$GATEWAY_NAME --tail=100
    
    - echo "🔍 Describe KrakenD Pod:"
    - kubectl describe pod -n "$NAMESPACE" -l app=$GATEWAY_NAME || true

    - echo "🔍 Mounted files inside container:"
    - POD_NAME=$(kubectl get pods -n "$NAMESPACE" -l app=$GATEWAY_NAME -o jsonpath="{.items[0].metadata.name}")
    - kubectl exec -n "$NAMESPACE" $POD_NAME -- ls -la /etc/krakend || true

    - echo "🔍 Actual krakend.json content:"
    - kubectl exec -n "$NAMESPACE" $POD_NAME -- cat /etc/krakend/krakend.json || true

    - echo "🔍 Environment Variables:"
    - kubectl exec -n "$NAMESPACE" $POD_NAME -- printenv | grep PORT || true
    
    - echo "🧾 krakend-config (as applied in cluster):"
    - kubectl get configmap krakend-config -n "$NAMESPACE" -o yaml || true

    - echo "🧾 Extract krakend.json from ConfigMap:"
    - kubectl get configmap krakend-config -n "$NAMESPACE" -o jsonpath='{.data.krakend\.json}' || true
    - echo ""
    - echo "🧪 Rendered krakend-config.yaml (after envsubst):"
    - envsubst < gateway/.k8s/krakend-config.yaml | sed -n '1,220p'
  
  
  
  
  
  
  
  
  
  timeout: 20 minutes
