variables:
  BACKEND_NAME: "todomanagement-api"
  NAMESPACE: "todo-test"
  IMAGE_PATH: "$CI_REGISTRY_IMAGE/${BACKEND_NAME}:${CI_PIPELINE_ID}"

# -------------------------
# BUILD & PUSH IMAGE
# -------------------------
build-backend:
  image: docker:27
  stage: build
  services:
    - name: docker:27.5.1-dind
      alias: docker
      command: ["--tls=false","--mtu=1410"]

  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

  tags:
    - k8s

  before_script:
    - echo -n "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

  script:
    - docker info
    - cd backend
    - docker build --pull -f TodoManagement.Api/Dockerfile -t "$IMAGE_PATH" .
    - docker push "$IMAGE_PATH" || docker push "$IMAGE_PATH"

  timeout: 20 minutes

# -------------------------
# DEPLOY BACKEND
# -------------------------
deploy-backend:
  stage: deploy-backend
  image: devopshepsiburada/kubectl:1.25.0
  tags:
    - k8s

  before_script:
    - kubectl config use-context $CI_PROJECT_ROOT_NAMESPACE/gitlab-agents:retail-hke-test

  script:
    - kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

    - kubectl get secret retail-gitlab -n "$NAMESPACE" >/dev/null 2>&1 || kubectl create secret docker-registry retail-gitlab --docker-server="$CI_REGISTRY" --docker-username="$DEPLOY_USERNAME" --docker-password="$DEPLOY_PASSWORD" -n "$NAMESPACE"

    - envsubst < backend/.k8s/mongo-deployment.yaml | kubectl apply -f -
    - envsubst < backend/.k8s/mongo-service.yaml | kubectl apply -f -
    - envsubst < backend/.k8s/redis-deployment.yaml | kubectl apply -f -
    - envsubst < backend/.k8s/redis-service.yaml | kubectl apply -f -
    - envsubst < backend/.k8s/deployment.yaml | kubectl apply -f -
    - envsubst < backend/.k8s/service.yaml | kubectl apply -f -
    - envsubst < backend/.k8s/ingress.yaml | kubectl apply -f -
    - kubectl get pods -n $NAMESPACE
    - POD_NAME=$(kubectl get pods -n $NAMESPACE -l app=$BACKEND_NAME -o jsonpath="{.items[0].metadata.name}")
    - kubectl describe pod $POD_NAME -n $NAMESPACE || true
    - kubectl logs $POD_NAME -n $NAMESPACE || true
    - kubectl get events -n todo-test --sort-by=.lastTimestamp
    - kubectl rollout status deployment/$BACKEND_NAME -n $NAMESPACE --timeout=120s
    
    
    
    
    
    


    - echo "📦 Backend Pod List:"
    - kubectl get pods -n "$NAMESPACE"
    - kubectl describe pod -n "$NAMESPACE" -l app=$BACKEND_NAME

    - echo "📜 Backend Logs:"
    - kubectl logs -n "$NAMESPACE" -l app=$BACKEND_NAME --tail=100 || true
    - kubectl get ingressclass
    - kubectl get pods -A | grep -i ingress
    - kubectl get svc -A | grep -i ingress
    - kubectl get ingress -n todo-test
    - kubectl get svc -n ingress-nginx
    - kubectl get svc todomanagement-api -n todo-test -o wide
    - kubectl get svc todomanagement-api -n todo-test -o yaml
    - kubectl get endpoints todomanagement-api -n todo-test
    - kubectl describe ingress todomanagement-api-ingress -n todo-test
    - kubectl get pods -n todo-test --show-labels
    - POD_NAME=$(kubectl get pods -n $NAMESPACE -l app=$BACKEND_NAME -o jsonpath="{.items[0].metadata.name}")
    - kubectl describe pod $POD_NAME -n $NAMESPACE || true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  timeout: 20 minutes
