apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: ${NAMESPACE}
  labels:
    app: krakend

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: krakend

  template:
    metadata:
      labels:
        app: krakend

    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: retail-gitlab

      containers:
        - name: krakend
          image: ${CI_REGISTRY_IMAGE}/krakend:${CI_PIPELINE_ID}
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend

      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
