apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: ${NAMESPACE}
  labels:
    app: krakend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: krakend

  template:
    metadata:
      labels:
        app: krakend

    spec:
      containers:
        - name: krakend
          image: krakend/krakend:2.9
          args: ["run", "-c", "/etc/krakend/krakend.json"]
          env:
            - name: PORT
              value: "8081"

          ports:
            - containerPort: 8081

          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend

      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
